Include unistd.h only if HAVE_UNISTD_H is defined
- Fixes compilation error, when building under Windows (e.g. VS2015):
  ..\src\rrd_create.c(18): fatal error C1083: Cannot open include file:
  'unistd.h': No such file or directory