Fix further build errors (MinGW-w64)
- rrd_list.c: MinGW-w64 does not provide glob.h (yet?)
  include win32/win32-glob.h using HAVE_GLOB_H. Fixes:
  rrd_list.c:9:10: fatal error: glob.h: No such file or directory
    #include <glob.h>
- rrd_update.c: MinGW has gettimeofday() in time.h. Fixes:
  rrd_update.c:46:12: error: conflicting types for 'gettimeofday'
    static int gettimeofday(
- rrd_tool.c: MinGW has not got getuid and mkdir only one argument.
  Fixes:
  rrd_tool.c:585:17: warning: nested extern declaration of 'getuid'
  rrd_tool.c:632:16: error: too many arguments to function 'mkdir'
    if(mkdir(argv[2], 0777)!=0){
- rrd_tool.h:
  MinGW-w64 provides localtime_r, ctime_r, gmtime_r, strtok_r
- rrd_graph.c: MinGW has strftime and tzname.
  Due to the resulting later include of time.h, fixes also:
  rrd_graph.c:1558: undefined reference to `localtime_r'
- rrd_client.c: MinGW does not provide realpath, "is_unix" excluded.
  Fixes:
  rrd_client.c:113: undefined reference to `realpath'
  rrd_client.c:130: undefined reference to `realpath'
- rrd_rpncalc.c: include pthread.h. Fixes e.g.:
  rrd_rpncalc.c:708: undefined reference to `localtime_r'