Update Makefile.msc, Windows build updates (#829)
* Add further Windows build files to .gitignore

- Added the following lines, sorted alphabetically:
  /win32/*.VC.db
  /win32/*.VC.opendb
  /win32/.vs
  /win32/DebugDLL
  /win32/Static\ Debug

* Update Makefile.msc for Windows builds with nmake

- Added comment with usage information on top of the file
- Fixed typo CCPFlags -> CPPFLAGS
- Changed from /TP (specifies C++ source files)
  to /TC (specifies C source files)
- Added zdll.lib gthread-2.0.lib pcre.lib to THIRD_PARTY_LIB
- Removed rrd_getopt.obj and rrd_getopt1.obj from RRD_LIB_OBJ_LIST
  added optparse.obj instead
- Added further required .obj files to RRD_LIB_OBJ_LIST
- Added deletion of win32\*.obj to the clean section
- Building of rrdcgi.exe: changed from rrd_getopt.obj
  and rrd_getopt1.obj to optparse.obj
- rc: include ./src, fixes:
  ./win32\rrd_config.h(119) : fatal error RC1015:
  cannot open include file 'mkstemp.h'.
- Added compilation of .c files in ./win32 folder

* Update librrd-4.vcxproj

- Removed ../contrib/include/libpng12 from AdditionalIncludeDirectories
  libpng12 has been updated to libpng14, but the include is not
  necessary, because png.h is found in ../contrib/include too
- Removed <ClCompile Include="..\src\win32comp.c" />
  definitions are already in rrd_thread_safe_nt.c
  Fixes win32comp.obj :
  error LNK2005: _localtime_r, _gmtime_r, _ctime_r, _strtok_r
  already defined in rrd_thread_safe_nt.obj
- Removed /FORCE:MULTIPLE, which is not required any more after removal
  of win32comp.c from compilation

* Update rrdtool.vcxproj

- Removed: IgnoreSpecificDefaultLibraries LIBCMTD.lib;LIBCMT.lib
  Fixes failing build in case of 'Debug|Win32'

* Update rrdupdate.vcxproj

- Added . to AdditionalIncludeDirectories for 'Static Debug|Win32'