Add prototype for bad_format_imginfo
This patch solve implicit declaration of function 'bad_format_imginfo'
warning introduced by commit 37d3050 "Added imginfo format check".

rrd_graph.c: In function 'rrd_graph_v':
rrd_graph.c:4025: warning: implicit declaration of function 'bad_format_imginfo'
rrd_graph.c:4025: warning: nested extern declaration of 'bad_format_imginfo'
rrd_graph.c: At top level:
rrd_graph.c:4836: warning: no previous prototype for 'bad_format_imginfo'