Allow empty imginfo string format
Commit 37d3050 "Added imginfo format check" breaks -f "" which used
to be very usefull to print data as text format on stdout. Allowing
an empty -f was particularly interesting because there was no
<width>x<height> printed out.

Before :

[root@nagios-2b ~]# rrdtool graph /dev/null -f "" --start -1d \
    DEF:d=/var/lib/rrd/nagios-2b/load.rrd:load5:AVERAGE \
    VDEF:v=d,AVERAGE \
    PRINT:v:%.6lf
5.284605

After :

[root@nagios-2b ~]# rrdtool graph /dev/null -f "" --start -1d \
    DEF:d=/var/lib/rrd/nagios-2b/load.rrd:load5:AVERAGE \
    VDEF:v=d,AVERAGE \
    PRINT:v:%.6lf
ERROR: bad format for imginfo