Add missing #define and indent rrd_open.c
- Add missing "#define __rrd_read(dst, dst_t, cnt) { \" after
  #elif defined(HAVE_LIBRADOS) && !defined(HAVE_MMAP)
- This fixes:
    indent: src/rrd_open.c:77: Error:Unmatched 'else'
    indent: src/rrd_open.c:79: Error:Stmt nesting error.
    and errors in case of defined(HAVE_LIBRADOS) && !defined(HAVE_MMAP)
- indent src/rrd_open.c using GNU indent 2.2.12
- Replace all remaining tabs by four spaces