Update Makefile.msc for Windows builds with nmake
- Added comment with usage information on top of the file
- Fixed typo CCPFlags -> CPPFLAGS
- Changed from /TP (specifies C++ source files)
  to /TC (specifies C source files)
- Added zdll.lib gthread-2.0.lib pcre.lib to THIRD_PARTY_LIB
- Removed rrd_getopt.obj and rrd_getopt1.obj from RRD_LIB_OBJ_LIST
  added optparse.obj instead
- Added further required .obj files to RRD_LIB_OBJ_LIST
- Added deletion of win32\*.obj to the clean section
- Building of rrdcgi.exe: changed from rrd_getopt.obj
  and rrd_getopt1.obj to optparse.obj
- rc: include ./src, fixes:
  ./win32\rrd_config.h(119) : fatal error RC1015:
  cannot open include file 'mkstemp.h'.
- Added compilation of .c files in ./win32 folder