Fix error 'optind': undeclared identifier
- Fixes compilation error, when building under Windows (e.g. VS2015):
  ..\src\rrd_tune.c(410): error C2065: 'optind': undeclared identifier
- Use options.optind instead of optind
  optind is a member of the struct options