Fix further build errors under Windows, updates (#828)
* Update WIN32-BUILD-TIPS.txt

- Modified links to newer versions of libraries
- Added links for pcre

* Update librrd-4.def

- rrd_flushall -> rrdc_flushall
- Added further exports
- Sorted alphabetically

* Update librrd-4.vcxproj

- Changed CompileAsCpp to CompileAsC
- Updated PlatformToolset from v120 to v140
- Added gthread-2.0.lib;pcre.lib to AdditionalDependencies
- Removed strftime=strftime_ from PreprocessorDefinitions
- Added /FORCE:MULTIPLE to AdditionalOptions for now
  Fixes win32comp.obj :
  error LNK2005: _localtime_r, _gmtime_r, _ctime_r, _strtok_r
  already defined in rrd_thread_safe_nt.obj
- Removed rrd_getopt.c and rrd_getopt1.c, added optparse.c
- Added further .c files to ClCompile, sorted alphabetically
- Removed rrd_getopt.h
- Added further .h files to ClInclude, sorted alphabetically

* Update rrdtool.vcxproj

- Updated PlatformToolset from v120 to v140
- Added intl.dll and pcre3.dll to copy PostBuildEvent

* Update rrdupdate.vcxproj

- Updated PlatformToolset from v120 to v140
- Added intl.dll and pcre3.dll to copy PostBuildEvent
- Added . to AdditionalIncludeDirectories for Debug|Win32

* Include win32-glob.h, dirent.h, asprintf.h (MSC)

- Fixes compilation errors, when building under Windows (e.g. VS2015):
  ..\src\rrd_list.c(4): fatal error C1083: Cannot open include file:
    'glob.h': No such file or directory
  ..\src\rrd_list.c(9): fatal error C1083: Cannot open include file:
    'dirent.h': No such file or directory
  librrd-4.lib(rrd_list.obj) : error LNK2001:
    unresolved external symbol _asprintf
- Added includes for Windows builds (MSC):
  "win32-glob.h" from https://sourceforge.net/projects/sox/
  "dirent.h"     from https://github.com/tronkko/dirent
  "asprintf.h"   from http://asprintf.insanecoding.org

* Add files required to build rrd_list.c (MSC)

The following files are added to the win32 directory
for building under Windows (e.g. VS2015):
- asprintf.c, asprintf.h, vasprintf-msvc.c
  from http://asprintf.insanecoding.org
- dirent.h
  from https://github.com/tronkko/dirent
- win32-glob.c, win32-glob.h
  from https://sourceforge.net/projects/sox/

* Remove spurious executable permission from README