Update Windows GitHub Actions
- Update ci-workflow.yml and add GitHub Actions for Windows builds
  using MSVC and vcpkg. Both, x64 and x86 builds are part of the CI.
  The required vcpkg ports are installed and cached using
  lukka/run-vcpkg@v7
- Add release-windows.yml, which enables building Windows binaries of
  RRDtool. This GitHub action is run automatically upon new tags and
  can be triggered manually. The required .exe and .dll files are
  copied using collect_rrdtool_vcpkg_files.bat and deployed by
  actions/upload-artifact@v2
- Makefile_vcpkg.msc:
  Add include\harfbuzz, which is required for building pango.
  Fixes: pango-coverage.h(28): fatal error C1083:
  Cannot open include file: 'hb.h': No such file or directory